### PR TITLE
re-generated code against v1.30.0

### PR DESCRIPTION
**Pull request by garethahealy**
- re-generated code against v1.30.0	
- updated actions to latest due to most running on deprecated node versions
- updated generate script to work within ci correctly and added ci to call it to validate it works correctly	
- fixed macos build issue due to 2 files with different case

https://github.com/quarkiverse/quarkus-authzed-client/issues/94

### CODE REVIEW

**Comment by garethahealy** [comment]
@gastaldi @iocanel can you review please

@sachin-bagla can you test this PR to see if it resolves your issue please

**Comment by garethahealy** [comment]
CI test `io.quarkiverse.quarkus.authzed.client.test.DevServicesAuthzedClientTest.shouldAccessDashboard` has been failing for past few months from PR history.

**Comment by garethahealy** [comment]
re-enabled metrics and http tests. dashboard is no longer supported on the image, so removed test:
- https://github.com/authzed/spicedb/blob/main/pkg/cmd/serve.go#L144

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by sachin-bagla** [comment]
> @gastaldi @iocanel can you review please
> 
> @sachin-bagla can you test this PR to see if it resolves your issue please

Thanks for looking into this @garethahealy 
I have cloned your repo in local and build quarkus-authzed-client-deployment-1.0.0-SNAPSHOT.jar locally from your repo  and able see both fields (limit, cursor) in quarkus-authzed-client-deployment-1.0.0-SNAPSHOT.jar. Please let me know once you released latest version for this.

**Comment by garethahealy** [comment]
@iocanel ; i dont see any conflicts highlighted...
Screenshot 2024-04-22 at 09 01 21

**Comment by iocanel** [comment]
I am seeing this:
2024-04-22_11:21:18_1689x828

But when I select `Create a merge commit` I am seeing exactly what you see. Anyway, I'll do that instead.

**Comment by sachin-bagla** [comment]
@garethahealy  Thanks for fixing this. I see PR is merged now. Which is latest official quarkus-authzed-client release version. 
I still seeing 0.3.0 is latest one   https://repo.maven.apache.org/maven2/io/quarkiverse/authzed/quarkus-authzed-client/

**Pull request merged**
